version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10
orbs:
  heroku: circleci/heroku@1.0.1 # Invoke the Heroku orb
workflows:
  heroku_deploy:
    environment:
      HEROKU_APP: "sleepy-refuge-55486" # define env var $HEROKU_APP
    jobs:
      - build
      - test
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
            - test
          filters:
            branches:
              only: sequential-branch-filter
  version: 2
 
jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  test:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run test
